### ISSUE TITLE
qwe

### ISSUE THREAD

**Issue by freeziyou** [gitmaya-test/test-gitmaya-to-lark#90]
利用prisma数据库建表  
针对 jike-sdk 完成mvp功能可行性测试

**Comment by blue-hope** [comment]
## Qwe MVP 用户流程与需求梳理

基于当前 issue 描述：`利用 prisma 数据库建表，针对 jike-sdk 完成 MVP 功能可行性测试`。仓库目前仅有 README 占位内容；以下为按“先验证 jike-sdk 可用性 + Prisma 持久化”的 MVP 范围拆解。

### 1. MVP 目标

验证一个最小可用闭环：

1. 用户提供/配置 Jike API 访问凭证。
2. 系统通过 `jike-sdk` 调用即刻 API。
3. 系统将用户、动态、评论等核心数据写入 Prisma 管理的数据库。
4. 用户可查看同步结果与基础运行状态。

> 注意：`open-jike/jike-sdk` README 标注“不再积极维护”，且需要 `endpointUrl`、`bundleId`、`buildNo`、`userAgent`、`accessToken` 等配置。因此 MVP 首要风险是 SDK/API 配置可用性与登录/鉴权稳定性。

### 2. 目标用户/角色

- **管理员/测试者**：配置 Jike API 参数、触发同步、查看结果与错误。
- **Jike 账号用户**：授权或提供 access token，用于拉取个人资料、关注动态、帖子、评论等数据。

### 3. 核心用户流程

#### Flow A：初始化与配置

1. 用户进入配置页/执行 CLI 初始化命令。
2. 填写 Jike SDK 必需配置：`endpointUrl`、`bundleId`、`buildNo`、`userAgent`。
3. 填写或刷新 `accessToken`。
4. 系统校验配置完整性。
5. 系统保存配置，并提示当前配置状态。

验收标准：

- 缺少必填配置时阻止保存并提示字段名。
- 配置保存后可被后续 API 调用复用。
- token 等敏感字段不得明文暴露在前端日志中。

#### Flow B：账号连通性验证

1. 用户点击“验证连接”或运行验证命令。
2. 系统调用 `api.users.profile()` 或等价 SDK 方法获取当前用户信息。
3. 系统将用户 profile upsert 到数据库。
4. 页面/终端展示验证成功、用户昵称/ID、更新时间；失败则展示错误原因。

验收标准：

- 成功时数据库存在当前 Jike 用户记录。
- 失败时可区分配置缺失、token 失效、网络/API 错误。

#### Flow C：同步关注动态/推荐动态

1. 用户选择同步类型：关注动态或推荐动态。
2. 系统调用 `personalUpdate.followingUpdates()` 或 `recommendFeed.list()`。
3. 系统解析返回的动态、作者、媒体信息。
4. 使用 Prisma upsert 写入用户、动态、媒体等表。
5. 展示同步条数、成功/失败数量、最近同步时间。

验收标准：

- 重复同步不会产生重复记录。
- 支持分页/游标的基础处理，至少能同步一页数据。
- 单条数据写入失败不应导致整批任务无提示地失败。

#### Flow D：同步动态详情与评论

1. 用户选择某条动态，点击“同步详情/评论”。
2. 系统调用 `posts.get(postId)` 获取动态详情。
3. 系统调用 `comments.listPrimary(postId)` 拉取一级评论；MVP 可选拉取子评论。
4. 系统写入/更新 post、comment、comment author 记录。
5. 页面展示评论数量、最近同步时间、错误信息。

验收标准：

- 可按 postId 查询本地已同步详情。
- 评论支持幂等写入。
- 评论与动态、作者建立可查询关系。

#### Flow E：查看本地数据

1. 用户进入数据列表页/运行查询命令。
2. 查看已同步的用户、动态、评论列表。
3. 可按作者、时间、关键词或同步批次筛选（MVP 至少支持按时间倒序）。
4. 点击动态查看详情和评论。

验收标准：

- 列表可分页。
- 动态详情能展示作者、正文、媒体、互动数、同步时间。
- 空状态和加载/错误状态明确。

### 4. MVP 功能需求

#### 4.1 配置与鉴权

- 支持保存 Jike SDK 运行配置。
- 支持设置/更新 access token。
- 支持调用 profile API 验证 token 是否可用。
- 可选：支持短信验证码登录或手机号密码登录，但建议 MVP 优先使用手动 token，降低实现复杂度。

#### 4.2 数据同步

- 同步当前用户 profile。
- 同步一页关注动态或推荐动态。
- 同步指定动态详情。
- 同步指定动态一级评论。
- 记录每次同步任务的状态、耗时、成功/失败数量。

#### 4.3 数据展示

- 展示当前连接账号信息。
- 展示同步任务日志。
- 展示本地动态列表与详情。
- 展示评论列表。

#### 4.4 错误处理

- SDK 配置缺失：提示需要补齐配置。
- token 失效：提示重新配置 token。
- API 限流/网络失败：记录错误并允许重试。
- 数据结构变更：记录原始 payload 便于排查。

### 5. 建议 Prisma 数据模型

MVP 可先建以下表，字段后续按 jike-sdk 实际响应补充：

- `JikeAccount`
  - `id`
  - `jikeUserId`，唯一
  - `screenName`
  - `avatarUrl`
  - `bio`
  - `rawProfileJson`
  - `createdAt` / `updatedAt`

- `JikePost`
  - `id`
  - `jikePostId`，唯一
  - `authorId`
  - `content`
  - `type`
  - `likedCount`
  - `commentCount`
  - `repostCount`
  - `postedAt`
  - `rawPostJson`
  - `createdAt` / `updatedAt`

- `JikeComment`
  - `id`
  - `jikeCommentId`，唯一
  - `postId`
  - `authorId`
  - `parentCommentId`，可空
  - `content`
  - `likedCount`
  - `commentedAt`
  - `rawCommentJson`
  - `createdAt` / `updatedAt`

- `JikeMedia`
  - `id`
  - `postId`
  - `type`
  - `url`
  - `thumbnailUrl`
  - `metadataJson`

- `SyncJob`
  - `id`
  - `type`：`PROFILE` / `FEED` / `POST_DETAIL` / `COMMENTS`
  - `status`：`PENDING` / `RUNNING` / `SUCCESS` / `FAILED`
  - `startedAt`
  - `finishedAt`
  - `successCount`
  - `failureCount`
  - `errorMessage`
  - `metadataJson`

- `ApiConfig`（如需数据库保存配置）
  - `id`
  - `endpointUrl`
  - `endpointId`
  - `bundleId`
  - `buildNo`
  - `userAgent`
  - `accessTokenEncrypted` 或改用环境变量/密钥管理
  - `createdAt` / `updatedAt`

### 6. 非功能需求

- **安全**：access token 必须加密保存或仅存环境变量；日志中脱敏。
- **幂等**：所有外部对象按 Jike 原始 ID upsert。
- **可观测性**：同步任务必须有状态、错误、耗时记录。
- **可恢复性**：同步失败可重试，不清空既有成功数据。
- **兼容性**：优先 Node.js >= 20.19.0，与 `jike-sdk` README 要求一致。
- **风险隔离**：由于 SDK 不再积极维护，保留 raw JSON 字段方便兼容 API 返回结构变化。

### 7. MVP 范围边界

#### 必做

- Prisma schema + migration。
- Jike SDK 配置加载。
- profile 连通性验证。
- 一页 feed 同步。
- 指定 post 的详情和一级评论同步。
- 基础数据/同步日志查看。

#### 暂不做

- 发布动态、点赞、关注/取关等写操作。
- 多账号复杂权限体系。
- 全量历史同步和复杂分页队列。
- 图片上传。
- 实时/定时任务调度。

### 8. 推荐实现顺序

1. 初始化项目依赖：Prisma、数据库、`jike-sdk`。
2. 建立 Prisma schema 并完成 migration。
3. 实现配置加载与 profile 验证。
4. 实现 feed 一页同步和 upsert。
5. 实现 post detail + comments 同步。
6. 实现最小 UI/CLI 查看同步结果。
7. 补充错误处理、日志脱敏、README 使用说明。

### 9. Definition of Done

- 本地能运行数据库迁移。
- 配置有效 Jike SDK 参数后，能成功获取当前用户 profile。
- 能将至少一页 Jike feed 写入数据库。
- 能对一条动态同步详情与一级评论。
- 数据重复同步不产生重复记录。
- 同步成功/失败均有 `SyncJob` 记录。
- README 说明如何配置、运行迁移、执行 MVP 验证。

**Comment by blue-hope** [comment]
## Qwe 技术实现方案（Prisma + jike-sdk MVP）

基于当前需求：**利用 Prisma 数据库建表，并针对 `jike-sdk` 完成 MVP 功能可行性测试**。仓库当前基本为空，因此建议先按“最小可验证闭环”搭建：配置 Jike SDK → 验证账号连通性 → 同步一页数据 → 入库 → 查询结果。

---

### 1. 技术目标

MVP 需要证明以下链路可行：

1. Node.js 服务能加载 Jike SDK 必需配置。
2. 能使用 access token 调用 `jike-sdk` 获取当前用户资料。
3. 能同步一页 feed/post/comment 数据。
4. 能用 Prisma 幂等写入数据库。
5. 能通过 CLI 或最小 HTTP API 查看同步结果与任务日志。

优先验证 SDK/API 可用性，UI 可后置。

---

### 2. 推荐技术栈

- Runtime：Node.js 20+
- Language：TypeScript
- Database：SQLite（MVP 默认，低成本本地验证）或 PostgreSQL（如需部署）
- ORM：Prisma
- SDK：`jike-sdk`
- 接口形态：优先 CLI + service layer；如需要页面，再补 Express/NestJS/Fastify
- 配置：`.env` + Prisma `ApiConfig` 表可选

建议 MVP 先使用 SQLite：

```env
DATABASE_URL="file:./dev.db"
JIKE_ENDPOINT_URL="..."
JIKE_BUNDLE_ID="..."
JIKE_BUILD_NO="..."
JIKE_USER_AGENT="..."
JIKE_ACCESS_TOKEN="..."
```

---

### 3. 模块划分

建议目录结构：

```txt
prisma/
  schema.prisma
  migrations/
src/
  config/
    env.ts
  jike/
    client.ts
    mapper.ts
    sync.service.ts
  prisma/
    client.ts
  jobs/
    sync-job.service.ts
  cli/
    index.ts
  server/                 # 可选：如需要 HTTP API
    app.ts
```

模块职责：

- `config/env.ts`：读取并校验 Jike SDK 和数据库配置。
- `jike/client.ts`：封装 jike-sdk 初始化，禁止业务层直接散落 SDK 创建逻辑。
- `jike/mapper.ts`：把 SDK 原始响应映射为 Prisma 写入数据。
- `jike/sync.service.ts`：负责 profile、feed、post detail、comment 同步流程。
- `jobs/sync-job.service.ts`：记录同步任务状态、耗时、成功/失败数量、错误信息。
- `cli/index.ts`：提供 MVP 验证命令。

---

### 4. Prisma 数据模型设计

MVP 先保留原始 JSON，避免 jike-sdk/API 字段变化导致返工。

```prisma
model JikeAccount {
  id             String   @id @default(cuid())
  jikeUserId     String   @unique
  screenName     String?
  avatarUrl      String?
  bio            String?
  rawProfileJson Json?
  createdAt      DateTime @default(now())
  updatedAt      DateTime @updatedAt

  posts          JikePost[]
  comments       JikeComment[]
}

model JikePost {
  id          String   @id @default(cuid())
  jikePostId  String   @unique
  authorId    String?
  content     String?
  type        String?
  likedCount  Int      @default(0)
  commentCount Int     @default(0)
  repostCount Int      @default(0)
  postedAt    DateTime?
  rawPostJson Json?
  createdAt   DateTime @default(now())
  updatedAt   DateTime @updatedAt

  author      JikeAccount? @relation(fields: [authorId], references: [id])
  comments    JikeComment[]
  media       JikeMedia[]

  @@index([postedAt])
  @@index([authorId])
}

model JikeComment {
  id              String   @id @default(cuid())
  jikeCommentId   String   @unique
  postId          String
  authorId        String?
  parentCommentId String?
  content         String?
  likedCount      Int      @default(0)
  commentedAt     DateTime?
  rawCommentJson  Json?
  createdAt       DateTime @default(now())
  updatedAt       DateTime @updatedAt

  post            JikePost      @relation(fields: [postId], references: [id])
  author          JikeAccount?  @relation(fields: [authorId], references: [id])
  parentComment   JikeComment?  @relation("CommentReplies", fields: [parentCommentId], references: [id])
  replies         JikeComment[] @relation("CommentReplies")

  @@index([postId])
  @@index([authorId])
  @@index([commentedAt])
}

model JikeMedia {
  id           String   @id @default(cuid())
  postId       String
  type         String?
  url          String
  thumbnailUrl String?
  metadataJson Json?
  createdAt    DateTime @default(now())

  post         JikePost @relation(fields: [postId], references: [id])

  @@unique([postId, url])
}

model SyncJob {
  id           String        @id @default(cuid())
  type         SyncJobType
  status       SyncJobStatus @default(PENDING)
  startedAt    DateTime?
  finishedAt   DateTime?
  successCount Int           @default(0)
  failureCount Int           @default(0)
  errorMessage String?
  metadataJson Json?
  createdAt    DateTime      @default(now())
  updatedAt    DateTime      @updatedAt

  @@index([type, status])
  @@index([createdAt])
}

model ApiConfig {
  id                   String   @id @default(cuid())
  endpointUrl           String
  endpointId            String?
  bundleId              String
  buildNo               String
  userAgent             String
  accessTokenEncrypted  String?
  createdAt             DateTime @default(now())
  updatedAt             DateTime @updatedAt
}

enum SyncJobType {
  PROFILE
  FEED
  POST_DETAIL
  COMMENTS
}

enum SyncJobStatus {
  PENDING
  RUNNING
  SUCCESS
  FAILED
}
```

> MVP 阶段可先不启用 `ApiConfig.accessTokenEncrypted`，改用环境变量保存 token，避免过早引入加密密钥管理复杂度。

---

### 5. Jike SDK 封装方案

`src/jike/client.ts` 只负责创建 SDK client：

```ts
export function createJikeClient() {
  const env = loadEnv();

  assertRequired(env.JIKE_ENDPOINT_URL, 'JIKE_ENDPOINT_URL');
  assertRequired(env.JIKE_BUNDLE_ID, 'JIKE_BUNDLE_ID');
  assertRequired(env.JIKE_BUILD_NO, 'JIKE_BUILD_NO');
  assertRequired(env.JIKE_USER_AGENT, 'JIKE_USER_AGENT');
  assertRequired(env.JIKE_ACCESS_TOKEN, 'JIKE_ACCESS_TOKEN');

  return createClient({
    endpointUrl: env.JIKE_ENDPOINT_URL,
    bundleId: env.JIKE_BUNDLE_ID,
    buildNo: env.JIKE_BUILD_NO,
    userAgent: env.JIKE_USER_AGENT,
    accessToken: env.JIKE_ACCESS_TOKEN,
  });
}
```

实现原则：

- SDK 初始化失败要抛出明确错误。
- token 相关内容不得打印完整值。
- 业务层只依赖封装后的 service，不直接依赖 SDK 方法名。

---

### 6. 同步流程设计

#### 6.1 Profile 连通性验证

命令：

```bash
pnpm qwe profile:verify
```

流程：

1. 创建 `SyncJob(PROFILE)`。
2. 初始化 Jike SDK。
3. 调用当前用户 profile API。
4. 将 profile upsert 到 `JikeAccount`。
5. 更新 SyncJob 为 `SUCCESS`；失败则写入 `FAILED + errorMessage`。

验收：

- 成功后数据库存在一条 `JikeAccount`。
- token 失效、配置缺失、网络失败能明确报错。

#### 6.2 Feed 一页同步

命令：

```bash
pnpm qwe feed:sync --type following
pnpm qwe feed:sync --type recommend
```

流程：

1. 创建 `SyncJob(FEED)`。
2. 调用 following feed 或 recommend feed。
3. 遍历返回项：
   - upsert 作者到 `JikeAccount`
   - upsert 动态到 `JikePost`
   - upsert 媒体到 `JikeMedia`
4. 单条失败只增加 `failureCount` 并记录 metadata，不能直接吞掉整批错误。
5. 保存游标/分页信息到 `SyncJob.metadataJson`。

验收：

- 重复同步同一页不会重复插入。
- 至少能成功同步一页数据。
- `SyncJob` 记录成功/失败数量。

#### 6.3 动态详情同步

命令：

```bash
pnpm qwe post:sync --post-id <jikePostId>
```

流程：

1. 创建 `SyncJob(POST_DETAIL)`。
2. 调用 post detail API。
3. upsert post、author、media。
4. 更新同步结果。

验收：

- 可按 `jikePostId` 查询本地详情。
- 已存在的 post 会被更新，不会重复创建。

#### 6.4 评论同步

命令：

```bash
pnpm qwe comments:sync --post-id <jikePostId>
```

流程：

1. 确认本地存在对应 post；不存在则先同步 post detail 或提示用户。
2. 调用一级评论列表 API。
3. upsert 评论作者。
4. upsert `JikeComment`。
5. 子评论可作为后续增强；MVP 先实现一级评论。

验收：

- 评论与 post、author 建立关系。
- 重复同步不产生重复评论。

---

### 7. MVP CLI 命令设计

建议先实现 CLI，降低 UI 成本：

```bash
pnpm qwe db:migrate
pnpm qwe profile:verify
pnpm qwe feed:sync --type following
pnpm qwe feed:list --limit 20
pnpm qwe post:sync --post-id <id>
pnpm qwe post:show --post-id <id>
pnpm qwe comments:sync --post-id <id>
pnpm qwe jobs:list --limit 20
```

如果需要 HTTP API，可在 CLI 验证完成后补充：

```txt
GET  /health
POST /sync/profile
POST /sync/feed
POST /sync/posts/:postId
POST /sync/posts/:postId/comments
GET  /posts
GET  /posts/:postId
GET  /jobs
```

---

### 8. 错误处理与日志策略

必须覆盖的错误类型：

- 配置缺失：启动前校验，提示缺失字段。
- token 失效：提示重新配置 token。
- SDK 方法不可用/返回结构变化：记录 `raw payload` 或错误上下文。
- 网络/API 限流：记录错误，允许重试。
- 数据写入失败：单条数据失败不应导致已成功数据回滚，除非是 schema 级错误。

日志要求：

- access token 只显示前 4 位和后 4 位，或完全不输出。
- 每个同步任务必须有 `SyncJob`。
- 失败的 job 必须包含可排查的 `errorMessage` 和必要 metadata。

---

### 9. 实现步骤拆分

#### Phase 1：项目初始化

- 初始化 Node + TypeScript 项目。
- 安装依赖：`prisma`、`@prisma/client`、`jike-sdk`、`dotenv`、CLI 参数库（如 `commander`）。
- 配置 lint/test/build 脚本。
- 添加 `.env.example`。

产出：项目可启动，`pnpm build` 通过。

#### Phase 2：Prisma schema 与迁移

- 新建 `prisma/schema.prisma`。
- 实现上述核心表。
- 执行 migration。
- 添加 Prisma client 单例。

产出：`pnpm prisma migrate dev` 成功，本地生成数据库。

#### Phase 3：Jike SDK 连通性验证

- 实现环境变量校验。
- 实现 `createJikeClient()`。
- 实现 `profile:verify`。
- profile 成功后 upsert `JikeAccount`。

产出：能获取当前账号 profile 并入库。

#### Phase 4：Feed 同步

- 实现 feed SDK 调用。
- 实现 feed item → Prisma mapper。
- 实现用户、post、media upsert。
- 添加 `feed:list` 查询本地数据。

产出：能同步并查看至少一页 feed。

#### Phase 5：Post detail 与 comments

- 实现 `post:sync`。
- 实现 `comments:sync`。
- 评论按 `jikeCommentId` 幂等写入。
- 添加 `post:show` 查询详情。

产出：能同步一条动态详情和一级评论。

#### Phase 6：收尾与文档

- 补充 README：环境变量、迁移、验证命令、常见错误。
- 补充最小测试：mapper、upsert 幂等、配置校验。
- 明确 SDK 不维护风险及 fallback 调试方式。

产出：他人按 README 可复现 MVP。

---

### 10. 测试计划

最小测试矩阵：

1. 配置缺失时，CLI 应失败并提示字段名。
2. token 无效时，`profile:verify` 创建失败 job。
3. token 有效时，`profile:verify` 成功 upsert 用户。
4. 重复运行 `feed:sync`，`JikePost` 数量不因同一原始 ID 重复增长。
5. `comments:sync` 重复运行，`JikeComment` 不重复。
6. SDK 返回字段缺失时，mapper 不应崩溃，原始 JSON 仍保存。

---

### 11. 主要风险与应对

| 风险 | 影响 | 应对 |
| --- | --- | --- |
| `jike-sdk` 不再积极维护 | API 可能不可用 | MVP 先验证 profile/feed；保留 raw JSON；SDK 封装隔离 |
| access token 获取方式不稳定 | 用户无法连接 | MVP 先支持手动 token，登录流程后置 |
| 返回结构与类型不明确 | Prisma 写入失败 | mapper 做字段兜底，raw JSON 入库 |
| API 限流或网络波动 | 同步失败 | SyncJob 记录失败并允许重试 |
| token 泄露 | 安全问题 | env 存储、日志脱敏，后续再加密入库 |

---

### 12. Definition of Done

- [ ] Prisma schema 已完成并可迁移。
- [ ] `.env.example` 包含所有 Jike SDK 必需配置。
- [ ] `profile:verify` 可调用 Jike API 并写入 `JikeAccount`。
- [ ] `feed:sync` 可同步至少一页动态并写入 `JikePost/JikeMedia`。
- [ ] `post:sync` 可同步指定动态详情。
- [ ] `comments:sync` 可同步指定动态一级评论。
- [ ] 重复同步不会产生重复数据。
- [ ] 每次同步都有 `SyncJob` 成功/失败记录。
- [ ] README 说明如何安装、配置、迁移、运行 MVP 验证命令。
